### ISSUE TITLE
add <defs><style></style></defs> support

### ISSUE THREAD

**Issue by codingBobo** [cppfw/svgren#103]

**Comment by igagis** [comment]
I'm not sure I understand the use case. Could you provide the full sample SVG file?

**Comment by codingBobo** [comment]
> such as this, i get all black pixels
>`<svg id="layer_1" data-name="layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><defs><style>.cls-1{fill:#47506a;fill-rule:evenodd;}.cls-2{fill:none;stroke:#3866f0;stroke-width:4px;}.cls-3{fill:#fff;fill-opacity:0;}</style></defs><g id="main"><g id="all_tools"><g id="group-24"><g id="v2_icon_award" data-name="v2 icon award"><path id="shape" class="cls-1" d="M24,1a20.15,20.15,0,0,1,9.52,37.83V47L24,41.25h0L14.48,47V38.83A20.15,20.15,0,0,1,24,1Zm0,4.79A15.34,15.34,0,1,0,39.24,21.12,15.29,15.29,0,0,0,24,5.79Z" transform="translate(0 0)"/><circle id="shapeColorSymbol" class="cls-2" cx="24" cy="21" r="8"/><rect id="rect" class="cls-3" width="48" height="48"/></g></g></g></g></svg>`

**Comment by igagis** [comment]
thanks, I'll have a look

**Comment by codingBobo** [comment]
> fixed in version `0.6.0`. Please also update `svgdom` to version `0.4.0`

thanks, i test it in my demo project, most of my svg file is works very well，but  still one resource has problem，the resource is:

`<svg id="layer_1" data-name="layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><defs><style>.cls-1,.cls-3{fill:none;}.cls-2,.cls-4{fill:#47506a;}.cls-3{stroke:#3866f0;stroke-width:4px;}.cls-4{fill-rule:evenodd;}</style></defs><g id="main"><g id="all tools"><g id="group-13"><g id="drive"><rect id="rect" class="cls-1" width="48" height="48"/><rect id="rect-2" data-name="rect" class="cls-2" x="12" y="32" width="24" height="4"/><g id="group-2"><polyline id="shapeColorSymbol" class="cls-3" points="13 27.29 18.61 23.34 23.74 26.92 32.26 20.41"/><polyline id="shapeColorSymbol-2" data-name="shapeColorSymbol" class="cls-3" points="26 19 33 19 33 26"/></g><path id="shape" class="cls-4" d="M36,6h9V39.76L40.76,44H7.24L3,39.76V6h9v5H8V39H40V11H36ZM19,3V13H14V3ZM34,3V13H29V3ZM27,6v5H21V6Z" transform="translate(0 0)"/></g></g></g></g></svg>`

**Comment by igagis** [comment]
Ok, I'll investigate

**Comment by igagis** [comment]
fixed in:
- `cssom` version `0.2.0`
- `svgdom` version `0.4.1`
- `svgren` version `0.6.1`

**Comment by codingBobo** [comment]
the issue is now fixed! Thank you so much
