### ISSUE TITLE
fatal error: rasterimage/image.hpp: No such file or directory

### ISSUE THREAD

**Issue by brechtsanders** [cppfw/svgren#107]
I have the latest version of all the dependencies but building versions 0.6.6 and 0.6.7 fails because it can't find `rasterimage/image.hpp`.
```
R:/winlibs64-13.1.0msvcrt/svgren-0.6.7/src/svgren/canvas.hxx:38:10: fatal error: rasterimage/image.hpp: No such file or directory
   38 | #include <rasterimage/image.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
```

Am I supposed to build against older versions of dependencies or where does `rasterimage/image.hpp` come from?

**Comment by igagis** [comment]
Hi!

`rasterimage` is a new dependency, you can find it here: https://github.com/cppfw/rasterimage

**Comment by igagis** [comment]
By the way, why do you build from sources? Which OS are you on?

**Comment by brechtsanders** [comment]
Okay it works now with rasterimage present in the system.

I'm on Windows 11 using MSYS2 shell but my own personal build of GCC (see https://winlibs.com/) as I'm building a package manager for GCC (and maybe also LLVM) for Windows (x86 / x86_64 / aarch64).
