### ISSUE TITLE
utki cocoapod doesn't have a lib

### ISSUE THREAD

**Issue by oziphantom** [cppfw/svgren#85]
so long tumbly rabbit hole of despair later. Cocoapods won't work because well CMake. So Duct Tape time. Gets pods, copy pod files to project, remove pods. Add files to project and link libs manually so we don't have to do the "workspace" thing. Only UTKI has no lib just the hpp files. So it won't link and I can't just add the hpp files because they are just hpp files. 

Where can I get the ios utki.a from?

**Comment by igagis** [comment]
The `.a` should be there in the package. If it is not there, then it is a bug. Let me check.

**Comment by igagis** [comment]
@oziphantom I've just checked, the package contains `.a` file:
https://dl.bintray.com/cppfw/cocoapods/utki/1.1.103/utki-1.1.103.zip

Do you use the new `cppfw` repo, or still the old one, which is `igagis`?

In case you use old repo, the latest package there is: https://dl.bintray.com/igagiscocoapods/utki/1.1.102/utki-1.1.102.zip
And it also contains the `.a` file.

**Comment by oziphantom** [comment]
hmm not the first time something something has not "downloaded and installed" on this mac. Maybe it is dodgier than I think it is. 

Solves the issue though. It actually Links and signs!

I will need to find a way to get "sponsoring" working ;)

**Comment by oziphantom** [comment]
So after much toil, and an update the product is now out if you wanted to have a look https://play.google.com/store/apps/details?id=com.symbolicone.ouille

for paying sponsorship doing a $1 month and having everybody take out fees is not ideal, international money fees etc. Do you have a paypal and I can just give you say 3 years in a single hit?

**Comment by igagis** [comment]
Wow, congratulations!
Very nice to see my software working in released product!

Yes, my paypal is `ivan.gagis@gmail.com`. Thanks for supporting my work :)!
