### ISSUE TITLE
Support for stroke-dasharray and stroke-dashoffset

### ISSUE THREAD

**Issue by VilleKrumlinde** [cppfw/svgren#86]
Hi,

Any plans to support stroke-dasharray and stroke-dashoffset?

One interesting use for these attributes is the animation effect of static images as demonstrated here:

https://maxwellito.github.io/vivus-instant/

and explained here:

https://css-tricks.com/svg-line-animation-works/

**Comment by igagis** [comment]
Let me investigate, perhaps implementing those is not that hard...

**Comment by igagis** [comment]
Implemented in:
- `svgren` version `0.5.5`
- `svgdom` version `0.3.52`

Now the libraries require C++'17 compatible compiler.

**Comment by VilleKrumlinde** [comment]
Thank you very much! Did you also see the email regarding this issue that I sent on Dec 22?

**Comment by igagis** [comment]
@VilleKrumlinde I have just found your email, it went to spam folder for some reason. I'll take a look at it. Could you create issues on github in future? It is just much more convenient and could help someone else with similar issues.
