### ISSUE TITLE
Unresolved external symbol

### ISSUE THREAD

**Issue by edqx** [cppfw/svgren#87]
Hi I'm having trouble building my project installing libsvgren through Nuget. I also had to change some of the internal code which is not ideal. I also had to install `r4` separately. Shouldn't this be a dependency?

Line 48 of `render.hpp` expected me to have `svgdom::SvgElement` instead of `svgdom::svg_element`.

I've uploaded an image for the first issue I was having, I've set my runtime library in both configuration places to `Multi-threaded Debug DLL (/MDd)`
![image](https://user-images.githubusercontent.com/60631511/107365382-a0e67180-6ad4-11eb-97b2-38bdf660082a.png)
![image](https://user-images.githubusercontent.com/60631511/107365507-ce331f80-6ad4-11eb-9628-85899ce94163.png)
![image](https://user-images.githubusercontent.com/60631511/107365529-d55a2d80-6ad4-11eb-9149-fea2b9a8fa17.png)

Thanks.

**Comment by edqx** [comment]
Here was a quick reproduction I made for the external symbol, if it's needed.
```c++
auto dom = svgdom::load(papki::FSFile("rifle.svg"));
auto result = svgren::render(*dom);

if (!sprite)
    D3DXCreateSprite(device, &sprite);
if (!sprite)
    D3DXCreateTexture(device, dom->width.value, dom->height.value, 0, D3DUSAGE_DYNAMIC, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, &texture);
RECT r{0, 0, dom->width.value, dom->height.value};
sprite->Begin(D3DXSPRITE_ALPHABLEND);
sprite->Draw(texture, &r, NULL, NULL, D3DCOLOR_RGBA(0, 0, 0, 255));
sprite->Flush();
sprite->End();
```

**Comment by igagis** [comment]
@edqx after you have installed the NuGet packages, did you update those to all latest versions?

The `svgren` is still considered in defelopment phase, so strict dependencies versions are not updated regularly, so one has to always install latest versions of packages.

The `r4` is a dependency in latest version of packages.

**Comment by edqx** [comment]
The latest version on NuGet is 0.5.6 which as far as I understand is the latest one, judging by GitHub tags.
![image](https://user-images.githubusercontent.com/60631511/107372367-3e45a380-6add-11eb-9252-e73b10b630b3.png)

**Comment by igagis** [comment]
@edqx how about all the other dependency packages? I meant those have to be latest version also.

**Comment by edqx** [comment]
Okay so my packages were indeed outdated, downloading the latest ones worked great. After a few std version errors, and switching my C++ standard to `latest` in my VS project settings, all build errors were fixed. Thanks for the quick reply and the work on this library.

**Comment by igagis** [comment]
Yes, it needs at least `C++17`. Great that it worked for you!
