### ISSUE TITLE
Not correctly displaying shapes.

### ISSUE THREAD

**Issue by edqx** [cppfw/svgren#88]
So I got everything building & working after my first issue, #87, although now I'm facing a problem where the SVG image is cut off half way. Originally I thought this was a problem with the way I was cropping the sprite during drawing, but now I'm not sure.
I've uploaded 2 images, the one that your renderer produces and another that my browser produces.
My code is relatively simple, I'm simply creating a D3DX texture and copying the bytes from the SVG image.
```c++
if (!texture)
{
	D3DXCreateTexture(Globals::device, result.dims.x(), result.dims.y(), 0, D3DUSAGE_DYNAMIC, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, &texture);

	D3DLOCKED_RECT d3drc; 
	texture->LockRect(0, &d3drc, NULL, 0);
	d3drc.Pitch >>= 2;
	memcpy(d3drc.pBits, result.pixels.data(), result.pixels.size());
	texture->UnlockRect(0);
}

D3DXMATRIX mat, orgmat;
sprite->GetTransform(&orgmat);
D3DXVECTOR2 vec4 = D3DXVECTOR2(100, 300);
D3DXMatrixTransformation2D(&mat, 0, 0,
	0, 0, 0,
	&vec4);
sprite->SetTransform(&mat);
sprite->Draw(texture, 0, NULL, NULL, D3DCOLOR_RGBA(255, 255, 255, 255));
sprite->SetTransform(&orgmat);
sprite->Flush();
sprite->End();
```

![image](https://user-images.githubusercontent.com/60631511/107403779-71982a80-6afd-11eb-9471-b7372a726192.png)
![image](https://user-images.githubusercontent.com/60631511/107403819-7f4db000-6afd-11eb-9ad1-9562f2459ca4.png)

This is just one example of one issue, if I instead use a very simple shape of 2 rectangles from the [MDN page on SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Basic_Shapes#rectangles)
I get an odd effect, like the width is incorrect, although I'm using the width and height from the SVG dom parser.
I'm using the same code here.
![image](https://user-images.githubusercontent.com/60631511/107404274-0733ba00-6afe-11eb-97a8-e9a4f0092138.png)
![image](https://user-images.githubusercontent.com/60631511/107404321-14e93f80-6afe-11eb-99e7-04caf65829ec.png)

**Comment by igagis** [comment]
@edqx could you attach the SVG file you are trying to render?

**Comment by edqx** [comment]
It's the SVG download from the one here https://www.flaticon.com/free-icon/rifle_486230.

**Comment by igagis** [comment]
@edqx I could render the rifle SVG correctly. Could you show your code where you actually prepare a nd do the rendering, i.e. call to `svgren::render()`?

**Comment by edqx** [comment]
Very simply,
```c++
std::unique_ptr<svgdom::svg_element> dom;
svgren::result result;
// ...
dom = svgdom::load(papki::fs_file("C:\\...\\rifle.svg"));
result = svgren::render(*dom);
```

**Comment by igagis** [comment]
@edqx I think I found the problem in your code from 0th post:

````cpp
memcpy(d3drc.pBits, result.pixels.data(), result.pixels.size());
````
you do `memcpy` and pass `result.pixels.size()` as the size of the memory to copy in bytes. But `result.pixels` contains `uint32_t` elements, so `size()` must be multiplied by `sizeof(uint32_t)`.

**Comment by edqx** [comment]
You're completely right, sorry for bothering you on something unrelated to svgren, I'm rendering it properly now, thanks.
The second issue with the square is still an issue though, would you know if this is an issue with svgren, or another trivial C++ bug?

**Comment by igagis** [comment]
No problem.

The rect SVG is also rendered properly at my end.
The resulting image you posted looks like there is something wrong with the width as you mentioned. Could you check that `result.dims.x(), result.dims.y()` you get are correct.

**Comment by edqx** [comment]
I've figured it out, it was an issue with the `D3DLOCKED_RECT.pBits` not being linear in memory. I instead used a function, shown below in case anyone else has the same issue as me. Thanks a lot for the help, and I apologise again for the trivial issues.

https://stackoverflow.com/questions/44255281/rgba-pixel-data-into-d3dlocked-rect
```c++
bool Drawing::ImageToTexture(uint8_t* src, size_t width, size_t height, LPDIRECT3DTEXTURE9 texture, size_t x, size_t y)
{
	D3DLOCKED_RECT d3drc;
	uint32_t* dest;

	if (FAILED(texture->LockRect(0, &d3drc, NULL, 0)))
		return false;

	d3drc.Pitch >>= 2;

	for (uint32_t row = 0; row < height; row++)
	{
		dest = (uint32_t*)d3drc.pBits + (row + y) * d3drc.Pitch + x;

		for (uint32_t col = 0; col < width; col++)
		{
			uint8_t r = *src++;
			uint8_t g= *src++;
			uint8_t b = *src++;
			uint8_t a = *src++;

			(*dest++) = b | (g << 8) | (r << 16) | (a << 24);
		}
	}

	texture->UnlockRect(0);
	return true;
}
```
