### ISSUE TITLE
compiling errors after update to the latest version

### ISSUE THREAD

**Issue by saeitsystems** [cppfw/svgren#91]
Hi,

after updating to the latest version of svgren and all the libraries I get a compiler error:

`CxImageSVG.cpp
K:\sae\nfs\software\packages\libutki.1.1.123\build\native\include\utki\span.hpp(242,54): warning C4003: not enough arguments for function-like macro invocation 'max'
K:\sae\nfs\software\packages\libutki.1.1.123\build\native\include\utki\span.hpp(242,54): error C2589: '(': illegal token on right side of '::'
K:\sae\nfs\software\packages\libutki.1.1.123\build\native\include\utki\span.hpp(269): message : see reference to class template instantiation 'utki::span<T>' being compiled
K:\sae\nfs\software\packages\libutki.1.1.123\build\native\include\utki\span.hpp(243,1): error C2059: syntax error: ')'
Done building project "Setit.vcxproj" -- FAILED.
`

I'm using visual studio 2019 with C++17
It would be great if you could fix this issue.

**Comment by igagis** [comment]
Hi,

this is because windows defines its own `max` macro, which is evil, macros must not have lower case names :).
Do you use the `max` macro somewhere in your program? In case you do, you should stop using it and start using the `std::max()` inline function.
Meanwhile, I will make a new version of `libutki` which undefines the `max` macro.

**Comment by igagis** [comment]
By the way, if you include the `windows.h` anywhere in your program, you can instead include the `<utki/windows.hpp>` which is provided by `libutki` for convenience. This header essentially includes the `windows.h`, but also undefines all sorts of problematic legacy macros defined by windows.

**Comment by saeitsystems** [comment]
That is what I did temporarily in my code as a workaround.
I could try the include `<utki/windows.hpp>` in stdafx.h but I think an additional undef  in span.h would help.

**Comment by igagis** [comment]
I added the undef to `span.hpp`. Version `1.1.124` of `libutki` should be release soon, see build https://github.com/cppfw/utki/actions/runs/732185427

**Comment by saeitsystems** [comment]
Ok, so I close the issue
