### ISSUE TITLE
VS2017 v141 toolset link failed

### ISSUE THREAD

**Issue by gaoqiangz** [cppfw/svgren#95]
![图片](https://user-images.githubusercontent.com/38213294/129439901-f010fcd0-715a-42a0-8ee2-2c5359d975d0.png)
![图片](https://user-images.githubusercontent.com/38213294/129439917-11059978-f9f8-4fc8-a920-9a3da7e01267.png)
I was upgrade from 0.4.49,my project still need support Windows XP...

**Comment by igagis** [comment]
I didn't put much efforts in supporting `v141` tools lately. But I will have a look at what can be done. I think it should be possible to fix it.

**Comment by igagis** [comment]
Unfortunately, `v141` tools have limited support of C++17, while the lib uses C++17 features missing from `v141` tools.

> my project still need support Windows XP

Do you mean that you need your app to work on windows XP or do you mean that Visual studio has to be run in Windows XP?

I think you can move to using `v142` tools, but compile your project for older windows.

**Comment by gaoqiangz** [comment]
> my project still need support Windows XP

It means that the EXE binary file of the project needs to run on Windows XP.
As far as I know, the v142 tool no longer supports XP.

> Unfortunately, v141 tools have limited support of C++17, while the lib uses C++17 features missing from v141 tools.

In addition, tools and language standards shouldn't be related, right? what limit are you referring to?

**Comment by gaoqiangz** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-160

**Comment by igagis** [comment]
> In addition, tools and language standards shouldn't be related, right?

this is true unless we are talking about Microsoft technologies, unfortunately... :(.

According to https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-160
in order to build for Windows XP, one needs `v141_xp` tools which I did never support in `svgren`.

I will try to release `svgren` version for `v141` tools as it was before.

**Comment by igagis** [comment]
I have added `v141` build to `svgren` version `0.5.20`. Do not forget to update all dependency libraries as well to latest versions.

**Comment by gaoqiangz** [comment]
Thanks a lot!
