### ISSUE TITLE
XCFramework support

### ISSUE THREAD

**Issue by lapfelix** [cppfw/svgren#97]
Now that arm64 Macs exist, iOS binaries now need two arm64 slices (one for arm64 iOS devices, one for arm64 Macs running the iOS simulator) and a fat binary can't contain two slices of the same architecture. The current Cocoapods integration relies on `.a` fat binaries. Apple's solution to this problem is XCFramework, which separates the binaries for different platforms in different folder in a framework package.

Otherwise, we can't compile for the iOS simulator on the new Macs with arm64 processors:
`building for iOS Simulator, but linking in object file built for iOS, file '~/myrepo/Pods/agg/lib/ios/libagg.a' for architecture arm64`

**Comment by igagis** [comment]
@lapfelix I have updated the packages, now those contain `xcframework` instead of fat library. I haven't tested it though.
Could you update your packages and try?

**Comment by lapfelix** [comment]
There seems to be an issue with `papki`, because the xcframework doesn't get added to my test xcodeproj so I get `Undefined symbol papki::xxxxxx` errors. However if I manually download the pre-built papki SVGFramework (from [here](http://gagis.hopto.org/repo/cppfw/cocoapods/papki-1.0.111.zip)) and drag it into Xcode it does work!

In our case though, we can't really use pre-built binaries because I realized yesterday that papki requires iOS 13 (and we still support iOS 12) because it uses new std::filesystem methods in a function. I fixed it in [my fork](https://github.com/lapfelix/papki/commit/29423cb52b6601041d1bbdb7fe73f74f84a4f037), but maybe there's a way to make it compatible with iOS 12 by using preprocessor directives to check if the new APIs are available. I can open a story in the papki repo about this specifically (and I could probably fix it myself).

But this is going to be great for iOS 13+ support.

**Comment by igagis** [comment]
Thanks for testing! I found that in `papki` I forgot to change library to framework in the `podspec`. I will fix it shortly.

As for iOS 13... before `sdt::filesystem` I had implementation via `dirent` API. I think I could revert it back. I'll make a new `papki` release today/tomorrow.

**Comment by igagis** [comment]
It actually appeared easier than I thought. I reverted back `dirent` implementation for iOS and now it supports `iOS 11.0`. I don't know, what is the minimum iOS version it is reasonable to support nowadays. Maybe even earlier `iOS` version could be enough, but I set `11.0` for now, as it is minimum one which does not produce `i386` binaries for simulator.

The new `papki` package of version `1.0.112` is release. Please update your packages and try. Let me know if it works or not. I'm aiming to provide smooth experience when using the libs, there should be no need to hack anything, just install the package.

**Comment by igagis** [comment]
Actually, I have updated iOS version to 9.0 in all packages

**Comment by lapfelix** [comment]
Hi, thank you so much! It works very well. We don't use Cocoapods but I just set up an empty project with the `svgren` pod, grabbed the xcframeworks and the headers from it and now we have `svgren` binaries that work with iOS devices and the iOS simulator on the new Macs.
