### ISSUE TITLE
Artifact when drawing SVG with `circle`

### ISSUE THREAD

**Issue by lapfelix** [cppfw/svgren#99]
I noticed an issue when using svgren to render one of our SVGs. This didn't happen with the older version of svgren we were using (that used cairo to render).

The attached SVG should render a circle, but it seems to render a square on the right of the circle:
<img width="50" alt="Screen Shot 2021-11-03 at 12 52 43 PM" src="https://user-images.githubusercontent.com/4634735/140110117-2663dbf0-9d0f-4aba-9250-25a082313735.png">

[11111111.svg.zip](https://github.com/cppfw/svgren/files/7469355/11111111.svg.zip)

What the SVG looks like:
```
<svg width="50" height="70" 
  xmlns="http://www.w3.org/2000/svg">
  <g transform="translate(10.755 9.526)" fill="none" fill-rule="evenodd">
    <circle stroke="#010101" stroke-width="2.5" cx="23.889" cy="20.036" r="4.624"/>
  </g>
</svg>
```

**Comment by igagis** [comment]
@lapfelix thanks for report! I have fixed it in `svgren` version `0.5.25`.

**Comment by igagis** [comment]
@lapfelix the issue can be closed, I suppose?

**Comment by lapfelix** [comment]
Yes the issue is now fixed! Thank you so much
